### ISSUE TITLE
Selector for [Country-Province-City]

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/react-eclipsefdn-members#22]
If using Selector, where the data come from? Using APIs?

**Comment by flora8984461** [comment]
My current list is downloaded from somewhere Github (Forgot where exactly I downloaded it). It might not be accurate...

**Comment by flora8984461** [comment]
How I am going to map country-province from backend?

**Comment by chrisguindon** [comment]
I think we need to split this request into 2 issues. We can use this one to discuss [Country-Province-City] and let's create a separate one for [Working Groups] and [Participation Level].

I am grouping [Working Groups] and [Participation Level] since they related.

@flora8984461 can you create the issue and re-purpose this one please?

**Comment by flora8984461** [comment]
> I think we need to split this request into 2 issues. We can use this one to discuss [Country-Province-City] and let's create a separate one for [Working Groups] and [Participation Level].
> 
> I am grouping [Working Groups] and [Participation Level] since they related.
> 
> @flora8984461 can you create the issue and re-purpose this one please?

@chrisguindon I separate wg to https://github.com/EclipseFdn/react-eclipsefdn-members/issues/27

**Comment by flora8984461** [comment]
https://www.npmjs.com/package/i18n-iso-countries
https://www.npmjs.com/package/countries-list


Seems both an option

**Comment by chrisguindon** [comment]
@linkfang @autumnfound,

It looks like we are currently using country-list. 

I think we are done for now!
