### ISSUE TITLE
Removing the first working group entry removes all entries

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/react-eclipsefdn-members#227]
When adding values to the WG section, if you have multiple entries and delete the first, all entries get deleted.

**Comment by linkfang** [comment]
I can't reproduce the issue on both React only mode and my local environment. 

By unchecking the check box, then yes, it will clear all the working groups. The checkbox is for the whole page/step.

By clicking on the "Remove this group", it should only delete that one.
![image](https://user-images.githubusercontent.com/43075439/127704158-ac041dc9-5ab5-4776-95ad-d0a5589fd940.png)

**Comment by linkfang** [comment]
For testing in local dev environment in API mode, before the [PR204](https://github.com/EclipseFdn/react-eclipsefdn-members/pull/204) being merged in, we need to do a minor change in src/Application/WorkingGroups/WorkingGroupsWrapper.js to make sure the wg can be properly shown on the page. (this is because of the wg data structure update)

![image](https://user-images.githubusercontent.com/43075439/128745379-c526b2e2-fcda-4bb8-9de3-590cf3ab2e66.png)

No need to do so after PR204 is merged.
And "React only mode" works fine without this change. (As the testing data was updated using the new wg data structure)

**Comment by autumnfound** [comment]
I was actually going to post about that. I wasn't able to reproduce on staging when I tried this morning, so it might be fixed now. Its not great that part of the UI is broken and is dependent on a PR to start working again, but I recognize that it's because of how we had to manage those change requests.
