### ISSUE TITLE
Navigating between steps when choose to continue existing form

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/react-eclipsefdn-members#48]
This is inspired from https://github.com/EclipseFdn/react-eclipsefdn-members/pull/21#issuecomment-790848753 .

If the user is starting over a new form, the right behavior is, he/she can navigate back and forth between those steps are finished and no errors, cannot move to steps further if prev step is not finished or has bad inputs. 

However, things differ when a user has an existing form with some steps finished. Let's say an example, the existing form has reached working groups, probably he /she wants to navigate to that step by clicking on the steppers. 

While it's hard to know which step he has reached last time without checking all the data, or something better is, have a stepReached field stored with the form entity.

**This featured might not needed at all.** 

But, if you want this behavior, it's better to have a field with the form entity (I mean the java code), stores the step the user has reached. I have not been able to think of a better way to do it.

**Comment by autumnfound** [comment]
Why not have a flow that loads each part of the form in order and validates it. Once it doesn't validate a step, that's the step you're on. Then it stops loading data since you probably haven't gotten farther. Its fine that loading a form takes a tick

**Comment by flora8984461** [comment]
You mean when the user chose an existing form, I start to try to load every step? That's weird, since I don't mount the step when you do not open it. My component mounts when you reach that page. 🤔

**Comment by autumnfound** [comment]
That would mean you'd have to double the number of calls you make to update the form state for every update. That doesn't seem like the right answer here unless we need to load to their last state exactly.

The data might need to be managed in a central controller, aka the higher common state between the steps, rather than the steps themselves. This would mean the data can be stored in the parent state if it exists and be seen by the step when loaded, rather than loaded after the step has been created. Is there a way to peek into a component maybe? Do a pre-mount operation?

**Comment by flora8984461** [comment]
In class component, there is something called `componentWillMount()` https://reactjs.org/docs/react-component.html#legacy-lifecycle-methods, but it's not recommended to use. 

`The data might need to be managed in a central controller, aka the higher common state between the steps,`  --> in that case, I need to fetch all the data before they load the first step.

**Comment by autumnfound** [comment]
Yeah they really hate the idea of pre-loading stuff. I get why, and this is an edge case, as we would have been using will mount to see if it would mount (which I'm pretty sure is the safer way of doing it). I don't like that they are removing it because they don't like it, that reeks of ivory tower architecture.

Maybe we need to update the form object to having interpreted fields, in that they don't get set by you. They would just hold IDs for the different objects that are related or whether they exist. I think this one can be put to the side safely as its a weird issue

**Comment by flora8984461** [comment]
`update the form object to having interpreted fields`   You mean for backend?

**Comment by chrisguindon** [comment]
I don't think we should store the last complete step.

In order to keep this simple, a user who comes back should always start at the beginning and will be expected to review his information from step 1.

The requirement is to pre-populate the input fields but it's not a requirement to load the last completed step.

This would be hard to implement, especially if we decide to deploy changes to our form after a user started to fill-up the form.

//cc @linkfang for visibility.
